config/routes.rb
Rails.application.routes.draw do
  resources :beerclubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'


  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :beerclub

  validate :user_not_in_club

  def user_not_in_club
    return if Membership.find_by(user_id:, beerclub_id:).nil?

    errors.add :user_id, "is already in the beerclub"
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @users = User.all
    @beerclubs = Beerclub.all
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to membership_url(@membership), notice: "Successfully joined the beerclub." }
        format.json { render :show, status: :created, location: @membership }
      else
        # TODO maybe doing something wrong but the variables of new need to be reinitialized here :D
        @users = User.all
        @beerclubs = Beerclub.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @user = @membership.user
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: "Successfully exited the group." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:user_id, :beerclub_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
      <%= form.label :user_id, class:"form-label", style: "display: block" %>
      <%= form.select :user_id, options_from_collection_for_select(@users, :id, :username), {:class => "form-select"} %>
  </div>

  <div>
    <%= form.label :beerclub_id, class:"form-label", style: "display: block" %>
    <%= form.select :beerclub_id, options_from_collection_for_select(@beerclubs, :id, :name), {:class => "form-select"}  %>
  </div>

  <div>
    <%= form.submit "Join this beerclub", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>User:</strong>
    <%= membership.user.username %>
  </p>

  <p>
    <strong>Beer club:</strong>
    <%= membership.beerclub.name %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to clubs", beerclubs_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to clubs", beerclubs_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>