config/routes.rb
Rails.application.routes.draw do
  resources :beerclubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'


  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true, length: { minimum: 3, maximum: 30 }
  validates :password, length: { minimum: 3 }
  validate :proper_characters_in_password?

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  def proper_characters_in_password?
    regex = "(?=.*[[:upper:]])(?=.*[0-9])"
    return false if password&.match(regex)

    errors.add :password, "doesn't contain uppercase letter and a number"
  end

  def favorite_style
    styles = favorite_attribute "styles"
    item_with_most_points(styles)
  end

  def favorite_brewery
    breweries = favorite_attribute "breweries"
    item_with_most_points(breweries)
  end

  private

  def favorite_attribute(target)
    # not the fastest implementation but its DRY complient

    items = {}
    ratings.each do |rating|
      style = Style.find_by_id rating.beer.style_id
      attributes = {
        # create hash with key being style name and value first 0 and then the score
        "styles" => style.name,
        # iterate through ratings and add scores depending on
        # which brewery the beer that was rated was made in
        "breweries" => rating.beer.brewery.name
      }

      raise "Incorrect target" if attributes[target].nil?

      if items[attributes[target]].nil?
        items[attributes[target]] = rating.score
      else
        items[attributes[target]] += rating.score
      end
    end
    items
  end

  def item_with_most_points(items)
    highest = { name: "", total: 0 }
    items.each do |item|
      if item[1] > highest[:total]
        highest[:name] = item[0]
        highest[:total] = item[1]
      end
    end
    highest[:name]
  end

  def self.top n
    sorted_by_rating_in_desc_order = User.all.sort_by{ |b| b.average_rating }.reverse.take(n)
  end

  def self.most_active n
    sorted_by_rating_count_in_desc_order = User.all.sort_by{ |b| b.count_ratings }.reverse.take(n)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    nil if @user == current_user
    # redirect_to user_path(@user), notice: "Not permitted to edit user"
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to signin_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy if @user == current_user

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user_path(user), class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path, class:"btn btn-primary" %>
<%= link_to "List of breweries", breweries_path, class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div>
  <p>
    <strong>Username:</strong>
    <%= @user.username %>
  </p>

  <p>
    Has made <%= pluralize(@user.ratings.count, "rating") %>, average rating <%= @user.average_rating %>
  </p>

  <p>
    <strong>ratings:</strong>
    <ul>
      <% @user.ratings.each do |r| %>
        <li>
          <%=r.beer.name %> <%= r.score %>
          <% if r.user == current_user %>
            <%= link_to "Delete", rating_path(r.id), class:"btn btn-danger", data: { "turbo-method": :delete} %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Beerclubs:</strong>
    <ul>
    <% @user.memberships.each do |m| %>
      <li>
        <%= link_to m.beerclub.name, beerclub_path(m.beerclub.id) %>
      </li>
    <% end%>
    </ul>
  </p>

  <%= link_to "Edit this user", edit_user_path(@user), class:"btn btn-primary" %>
  <%= link_to "Back to users", users_path, class:"btn btn-primary" %>

  <%= button_to "Destroy this user", @user, class:"btn btn-danger", method: :delete %>
</div>