config/routes.rb
Rails.application.routes.draw do
  resources :beerclubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/', to: 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'


  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/beerclub.rb
class Beerclub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :membership

  validates :name, presence: true
  validates :founded, numericality: { greater_than_or_equal_to: 1040,
                                      only_integer: true }
  validate :creation_year_not_in_future

  def creation_year_not_in_future
    return unless founded > Time.now.year

    errors.add :founded, "cannot be in the future"
  end
end

app/controllers/beerclubs_controller.rb
class BeerclubsController < ApplicationController
  before_action :set_beerclub, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beerclubs or /beerclubs.json
  def index
    @beerclubs = Beerclub.all
  end

  # GET /beerclubs/1 or /beerclubs/1.json
  def show
    @membership = @beerclub.memberships.find_by user_id: current_user
  end

  # GET /beerclubs/new
  def new
    @beerclub = Beerclub.new
  end

  # GET /beerclubs/1/edit
  def edit
  end

  # POST /beerclubs or /beerclubs.json
  def create
    @beerclub = Beerclub.new(beerclub_params)

    respond_to do |format|
      if @beerclub.save
        format.html { redirect_to beerclub_url(@beerclub), notice: "Beerclub was successfully created." }
        format.json { render :show, status: :created, location: @beerclub }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beerclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beerclubs/1 or /beerclubs/1.json
  def update
    respond_to do |format|
      if @beerclub.update(beerclub_params)
        format.html { redirect_to beerclub_url(@beerclub), notice: "Beerclub was successfully updated." }
        format.json { render :show, status: :ok, location: @beerclub }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beerclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beerclubs/1 or /beerclubs/1.json
  def destroy
    @beerclub.destroy

    respond_to do |format|
      format.html { redirect_to beerclubs_url, notice: "Beerclub was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beerclub
    @beerclub = Beerclub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beerclub_params
    params.require(:beerclub).permit(:name, :founded, :city)
  end
end

app/helpers/beerclubs_helper.rb
module BeerclubsHelper
end

app/views/beerclubs/_beerclub.html.erb
<div id="<%= dom_id beerclub %>">
  <p>
    <strong>Name:</strong>
    <%= beerclub.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beerclub.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beerclub.city %>
  </p>

  <p>
    <strong>Members:</strong>
    <ul>
      <% beerclub.memberships.each do |m| %>
        <li>
          <%= link_to m.user.username, user_path(m.user.id) %>
        </li>
      <% end%>
    </ul>
  </p>

</div>

app/views/beerclubs/_form.html.erb
<%= form_with(model: beerclub) do |form| %>
  <% if beerclub.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beerclub.errors.count, "error") %> prohibited this beerclub from being saved:</h2>

      <ul>
        <% beerclub.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class:"form-label", style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :founded, class:"form-label", style: "display: block" %>
    <%= form.number_field :founded, class:"form-control" %>
  </div>

  <div>
    <%= form.label :city, class:"form-label", style: "display: block" %>
    <%= form.text_field :city, class:"form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beerclubs/edit.html.erb
<h1>Editing beerclub</h1>

<%= render "form", beerclub: @beerclub %>

<br>

<div>
  <%= link_to "Show this beerclub", @beerclub %> |
  <%= link_to "Back to beerclubs", beerclubs_path %>
</div>

app/views/beerclubs/index.html.erb
<h1>Beerclubs</h1>

<div id="beerclubs">
  <% @beerclubs.each do |beerclub| %>
    <%= render beerclub %>
    <p>
      <%= link_to "Show this beerclub", beerclub, class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to("New beerclub", new_beerclub_path, class:"btn btn-primary") if current_user %>

app/views/beerclubs/new.html.erb
<h1>New beerclub</h1>

<%= render "form", beerclub: @beerclub %>

<br>

<div>
  <%= link_to "Back to beerclubs", beerclubs_path %>
</div>

app/views/beerclubs/show.html.erb
<%= render @beerclub %>

<div>
  <% if current_user %>
    <% if @membership.nil? %>
      <%= form_with model: Membership.new do |form| %>
        <%= form.hidden_field :beerclub_id, value: @beerclub.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.submit "Join the beer club", class:"btn btn-primary" %>
      <% end %>
    <% else %>
      <%= form_with(model: @membership, method: :delete) do |form| %>
        <%= form.hidden_field :beer_club_id, value: @beerclub.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.submit "End the membership", class:"btn btn-danger" %>
      <% end %>
    <% end %>

  <% else %>
    <p>Log in to join this beerclub</p>
  <% end %>
</div>

<br>

<div>
  <%= link_to("Edit this beerclub", edit_beerclub_path(@beerclub), class:"btn btn-primary") if current_user %>
  <%= link_to "Back to beerclubs", beerclubs_path, class:"btn btn-primary"%>

  <%= button_to "Destroy this beerclub", @beerclub, class:"btn btn-danger", method: :delete if current_user %>
</div>